import{a as P,S as $}from"./assets/vendor-DMAHcxl-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function m(r,t){return(await P.get("https://pixabay.com/api/",{params:{key:"55036420-a7a19d5751e273048ff10c958",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const f=document.querySelector(".loader"),p=document.querySelector(".gallery");let q=new $(".gallery .photo-card a",{captionsData:"alt",captionDelay:250});function g(r){function t(e){const{webformatURL:o,tags:n,likes:L,views:w,comments:v,downloads:b,largeImageURL:S}=e;return`<li class="photo-card">
              <a href=${S}><img src="${o}" alt="${n}"/></a>

              <div class="info">
              <div class="info-item"><h2>Likes: <span>${L}</span></h2></div>
              <div class="info-item"> <h2>Views: <span>${w}</span></h2></div>
              <div class="info-item"><h2>Comments: <span>${v}</span></h2></div>
              <div class="info-item"><h2>Downloads: <span>${b}</span></h2></div>
            </div>
            </li>
            `}function a(e){return e.map(t).join("")}const i=a(r);p.innerHTML=i,q.refresh()}function D(){p.innerHTML=""}function h(){f.classList.remove("is-hidden")}function d(){f.classList.add("is-hidden")}function x(){btnLoad.classList.remove("is-hidden")}function B(){btnLoad.classList.add("is-hidden")}function y(){page>=totalPages&&(s("We're sorry, but you've reached the end of search results."),B())}function s(r){iziToast.show({message:r,position:"topRight",backgroundColor:"rgba(232, 13, 13, 0.8)",messageColor:"white"})}const u=document.querySelector(".form"),E=document.querySelector(".load"),O=15;let l,c,R;u.addEventListener("submit",T);//! ========================================
async function T(r){if(r.preventDefault(),c=new FormData(u).get("search-text").trim(),h(),c===""){s("Please enter a search term");return}l=1,D(),h();try{const a=await m(c,l);if(R=Math.ceil(a.totalHits/O),!a.hits.length){s("Sorry, there are no images matching your search query.Please try again!");return}g(a.hits),y(),x()}catch(a){console.log(a),s("Something went wrong!")}finally{d(),u.reset()}}//! ========================================
E.addEventListener("click",C);async function C(r){r.preventDefault(),l+=1;try{const t=await m(c,l);g(t.hits),y(),M()}catch{d(),s("Something went wrong!")}d()}function M(){const t=document.querySelector(".photo-card").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
