import{a as D,S as $}from"./assets/vendor-DMAHcxl-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function h(r,t){return(await D.get("https://pixabay.com/api/",{params:{key:"55036420-a7a19d5751e273048ff10c958",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const m=document.querySelector(".loader"),f=document.querySelector(".gallery");let x=new $(".gallery .photo-card a",{captionsData:"alt",captionDelay:250});function p(r){function t(e){const{webformatURL:o,tags:n,likes:v,views:b,comments:S,downloads:P,largeImageURL:q}=e;return`<li class="photo-card">
              <a href=${q}><img src="${o}" alt="${n}"/></a>

              <div class="info">
              <div class="info-item"><h2>Likes: <span>${v}</span></h2></div>
              <div class="info-item"> <h2>Views: <span>${b}</span></h2></div>
              <div class="info-item"><h2>Comments: <span>${S}</span></h2></div>
              <div class="info-item"><h2>Downloads: <span>${P}</span></h2></div>
            </div>
            </li>
            `}function a(e){return e.map(t).join("")}const c=a(r);f.innerHTML=c,x.refresh()}function B(){f.innerHTML=""}function E(){m.classList.remove("is-hidden")}function d(){m.classList.add("is-hidden")}function g(){btnLoad.classList.remove("is-hidden")}function y(){btnLoad.classList.add("is-hidden")}function s(r){iziToast.show({message:r,position:"topRight",backgroundColor:"rgba(232, 13, 13, 0.8)",messageColor:"white"})}const u=document.querySelector(".form"),O=document.querySelector(".load"),R=15;let i,l,L;u.addEventListener("submit",T);//! ========================================
async function T(r){if(r.preventDefault(),l=new FormData(u).get("search-text").trim(),E(),l===""){s("Please enter a search term"),d();return}i=1,B(),y();try{const a=await h(l,i);if(L=Math.ceil(a.totalHits/R),!a.hits.length){s("Sorry, there are no images matching your search query.Please try again!");return}p(a.hits),w(),g()}catch(a){console.log(a),s("Something went wrong!")}finally{d(),u.reset()}}//! ========================================
O.addEventListener("click",C);async function C(r){r.preventDefault(),i+=1;try{const t=await h(l,i);p(t.hits),w(),g(),M()}catch{d(),s("Something went wrong!")}d()}function M(){const t=document.querySelector(".photo-card").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}function w(){i>=L&&(s("We're sorry, but you've reached the end of search results."),y())}
//# sourceMappingURL=index.js.map
